require 'locomotive/middlewares/fonts'
require 'locomotive/middlewares/seo_trailing_slash'
require 'locomotive/middlewares/cache'
require 'locomotive/middlewares/inline_editor'
require 'locomotive/middlewares/plugins/collection_prefix'
require 'locomotive/middlewares/plugins/mountpoint'
